retinanet-9
RUST_BACKTRACE=1 target/release/zm-aidect
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Evaluating #903 "Upsample_344" Unimplemented(Upsample)

Caused by:
    stateless evaluation not implemented', src/main.rs:207:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   3: zm_aidect::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
zsh: exit 101   RUST_BACKTRACE=1 target/release/zm-aidect